// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsobWr-CSCyTz9nYR_rlFdJzl7ZHa9u8w',
    appId: '1:691522441887:web:7b597abcab6037231008aa',
    messagingSenderId: '691522441887',
    projectId: 'flotter-test-cda',
    authDomain: 'flotter-test-cda.firebaseapp.com',
    storageBucket: 'flotter-test-cda.firebasestorage.app',
    measurementId: 'G-RDXRNF4JZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwNL1gCRSdslthKqbcJzzfKkfhXKHciEo',
    appId: '1:691522441887:android:9687c161057654501008aa',
    messagingSenderId: '691522441887',
    projectId: 'flotter-test-cda',
    storageBucket: 'flotter-test-cda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLm4-sxHd4hD1_URl0kNjUnKL7kD0rSQQ',
    appId: '1:691522441887:ios:8ca105dbe86689371008aa',
    messagingSenderId: '691522441887',
    projectId: 'flotter-test-cda',
    storageBucket: 'flotter-test-cda.firebasestorage.app',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLm4-sxHd4hD1_URl0kNjUnKL7kD0rSQQ',
    appId: '1:691522441887:ios:8ca105dbe86689371008aa',
    messagingSenderId: '691522441887',
    projectId: 'flotter-test-cda',
    storageBucket: 'flotter-test-cda.firebasestorage.app',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsobWr-CSCyTz9nYR_rlFdJzl7ZHa9u8w',
    appId: '1:691522441887:web:4e161ed167f252361008aa',
    messagingSenderId: '691522441887',
    projectId: 'flotter-test-cda',
    authDomain: 'flotter-test-cda.firebaseapp.com',
    storageBucket: 'flotter-test-cda.firebasestorage.app',
    measurementId: 'G-CGKM4ESV9B',
  );
}
